#!/bin/bash
## Octave-Forge: miscellaneous package bootstrap script
## Run this to generate the configure script

set -e      # halt if unhandled error
aclocal -I m4
autoconf    # generate configure script
autoheader -f
